name: MobRacers
main: me.winterguardian.mobracers.MobRacersPlugin
version: 1.1.39
description: A minecraft race game with mobs as vehicles !
author: WinterGuardian
softdepend: [Core, PlaceHolderAPI, Vault]
load: POSTWORLD
