#
#Bonjour et bienvenue à la configuration de BlockFarmers
#Si vous voulez réinitialiser ce ficher, supprimez le et rechargez le plugin
#

#Ceci est la longueur des pauses entre chaques parties
#default: 15
waiting-timer: 15

#Ceci est la longueur du moment en fin de partie où les feux d'artifices apparaissent
#default: 5
clapping-timer: 5

#Ceci est la liste des blocs qui peuvent être labourés en jeu, vous devez spécifier le nom du matériau et le data
#
#Exemple:
#farmable-blocks:
# - GRASS:0
# - DIRT:1
# - WOOD:5
#
#Vous devez utiliser les nombs bukkit et non les noms vanilla
#La liste des matériaux peut être consulté ici http://kiwike.se/wiki/index.php/Item_Names
farmable-blocks:
  - GRASS:0

#Ce mode auto-join permet aux joueurs de rejoindre instantanément le jeu en rejoinant le serveur.
#Optimal pour les réseaux BungeeCord où BlockFarmers est seul sur votre serveur
#Les joueurs avec la permission de staff/admin (BlockFarmers.staff) ne sont pas redirigé directement en jeu et ils peuvent quitter en utilisant la command
auto-join: false

#Puisque les stats ne se synchronisent pas entre les serveurs, you voudrez peut être les désactiver dans des grands réseaux BungeeCord avec plusieurs serveurs BlockFarmers
enable-stats: true

#Le mode teleport-join permet aux joueurs de rejoindre quand ils se font téléporter dans la région et de quitter quand ils se font téléporter en dehors
#Parfait pour des serveurs de type Multiverse avec des portails pour rejoindre les jeux
#Les joueurs avec la permission de staff/admin (BlockFarmers.staff) ne sont pas redirigé directement en jeu quand ils sont téléportés dans la région
teleport-join: true

#Si vous activez ceci, les joueurs seront en rouge dans la liste des joueurs et ils auront un entête et un pied dans la liste des joueurs (tab) donnant quelques infos sur le jeu
color-in-tab: true

#Ceci est la fonctionnalité pour bloquer des commandes pour les joueurs en jeu seulement. Vous pouvez modifier ensuite la liste des commandes qui ne seront pas bloquées si vous activez cette fonctionnalité.
block-commands: true
allowed-commands:
  - mobracers
  - mr
  - reload
  - ban
  - mute
  - kick

#Voulez vous utilisez les noms ou les "displaynames" ? Les displaynames peuvent inclure le surnom essentials et le grade du joueur
use-displaynames: false

#Le nombre minimum de joueurs ne peut être plus petit que 2 et le maximum ne peut être plus grand que 16
min-players: 2
max-players: 8

#Le message d'invitation est un message envoyé à tout les joueurs du serveur lors que des joueurs souhaitent faire une partie (en rejoignant). 
#Il y a une mesure d'anti spam empêchant le message d'être envoyé si il a déjà été envoyé il y a moins de 30 secondes
invitation-message: false

#Vous pouvez mettre une étoile "*" pour désigner tout les mondes ou "null" pour envoyer ces messages seulement aux joueurs en jeu
#Ceci est la liste des mondes dans lesquels vous voulez voir les messages d'invitation et de victoire 
#Si vous incluez une liste de mondes, organisez les tel une liste de châines de texte comme pour la liste des commandes ci-dessus
broadcast-worlds: "*"

#Voulez vous enregistrer les états des joueurs pour qu'ils reprennent tout après avoir jouer ? true/false
#Cette option est optimale pour le factions, elle permet de conserver l'inventaire de chaque joueurs
#Il n'y a plus moyen d'obtenir de la vie ou de la nourriture en profitant de MobRacers avec cette option d'activée
#De plus, cette option vous permet de sauter l'étape de mettre une sortie au jeu puisque les joueurs sont téléportés à leur ancienne position
#Liste des trucs enregistrés par cette fonctionnalité:
#La position, la vélocité et la distance de chute
#L'inventaire, l'armure et même l'item sur le curseur
#La vie, la nourriture, la saturation de la nourriture et la fatigue
#Les ticks de feu et le temps d'air qu'il lui reste à respirer
#Le mode de jeu, sa permission de voler et son vol lui même
#Sa vitesse de marche et de vol
#Tout ses effets de potions
keep-player-states: false

#Cette option laisse MobRacers changer le MOTD du serveur
#Les messages utilisés comme MOTDs sont configurable dans le fichier lang
#aux lignes: standby-status, arenaselect-status, vehicleselect-status et game-status
#Ceci peut être énormément utile pour les réseaux Bungee avec plusieurs serveurs
#où il y a besoin de montrer l'état du jeu
enable-motd: false

#Configure la connexion de BlockFarmers à une base de données
#Désactiver le SQL sans désactiver les stats plus haut utilise les
#userdatas en fichier YAML pour sauvegarder les stats
#Le plugin supportes presque tout les bases de données tant qu'elles
#sont compatible JDBC
#
#Exemples de drivers & et d'urls:
#  com.mysql.jdbc.Driver
#  jdbc:mysql://localhost:3306/yourdatabase
#
#  org.sqlite.JDBC
#  jdbc:sqlite:/C:/Users/you/yourdatabase
#
sql-enabled: false
sql-driver: com.example.jdbc.Driver
sql-url: jdbc:example://localhost:3306/minecraft_db
sql-user: blockfarmers_admin
sql-password: secret


#Vous pouvez les commandes de fin de partie pour adapter BlockFarmers à l'économie de votre serveur
#Le nom du gagnant est représenté par <winner>
#
#Retirez les '#' pour activer les commandes
#endgame-commands:
#  - 'give <winner> minecraft:diamond 1'